const Roles = {
  SYSADMIN: "SYSADMIN",
  COORDINATOR: "COORDINATOR",
  COORDINATORASSISTANT: "COORDINATORASSISTANT",
  STUDENT: "STUDENT",
  COMPANY: "COMPANY",
  COMPANYSUPERVISOR: "COMPANYSUPERVISOR",
};

export default Roles;
